version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 8009:80
    environment:
      - DATABASE_URL=postgresql://postgres_prod:postgres_prod@db:5432/postgres_prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - ./data_prod/db:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres_prod
      - POSTGRES_PASSWORD=postgres_prod
      - POSTGRES_DB=postgres_prod
